build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.16
  amd64: ghcr.io/home-assistant/amd64-base:3.16
  armhf: ghcr.io/home-assistant/armhf-base:3.16
  armv7: ghcr.io/home-assistant/armv7-base:3.16
  i386: ghcr.io/home-assistant/i386-base:3.16
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Openpilot Installer Generator"
  org.opencontainers.image.description: "Host the openpilot installer generator on your local network"
  org.opencontainers.image.source: "https://github.com/yourusername/hassio-addon-openpilot-installer"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"